import type { NextPage } from "next";
import Head from "next/head";
import { AppContainer } from "../components/Layout/AppContainer";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pablo Endara-Santiago</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppContainer />
    </div>
  );
};

export default Home;
